FROM node:18.13.0

ARG UID

RUN npm i -g @nestjs/cli

# Create user with same permissions as host and some useful stuff
RUN adduser -u ${UID} --disabled-password --gecos "" appuser
RUN mkdir /home/appuser/.ssh
RUN chown -R appuser:appuser /home/appuser/
RUN echo "StrictHostKeyChecking no" >> /home/appuser/.ssh/config

RUN npm install nodemon -g
RUN usermod -aG node appuser